# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

det_sympd_C <- function(x) {
    .Call(`_ramses_det_sympd_C`, x)
}

.dmnorm_C <- function(y, mu, cov_prec, is_cov) {
    .Call(`_ramses_dmnorm_C`, y, mu, cov_prec, is_cov)
}

.update_gp_C <- function(y, R12, R22, mu1, mu2) {
    .Call(`_ramses_update_gp_C`, y, R12, R22, mu1, mu2)
}

